/***************************************************************************//**
 *   @file   parameters.h
 *   @brief  Platform dependent parameters.
 *   @author Prerna Baranwal, plain spi
*/

#define _PARAMETERS_H_



#define UART_BAUDRATE                           115200
#ifdef PLATFORM_MB
#define SPI_DEVICE_ID				XPAR_SPI_0_DEVICE_ID
//#define GPIO_DEVICE_ID				XPAR_GPIO_0_DEVICE_ID
#define UART_DEVICE_ID				XPAR_AXI_UART_DEVICE_ID

//#define GPIO_OFFSET				0
// modifying it for only dac 
//#define ADC_DDR_BASEADDR			(XPAR_AXI_DDR_CNTRL_BASEADDR + 0x800000)
//#define DAC_DDR_BASEADDR			(XPAR_AXI_DDR_CNTRL_BASEADDR + 0x900000) // condition for microblaze
//#else
#define SPI_DEVICE_ID				XPAR_XSPIPS_0_DEVICE_ID
//#define GPIO_DEVICE_ID				XPAR_XGPIOPS_0_DEVICE_ID
#define UART_DEVICE_ID				XPAR_XUARTPS_0_DEVICE_ID
#define UART_IRQ_ID				XPAR_XUARTPS_1_INTR

#define INTC_DEVICE_ID				XPAR_SCUGIC_SINGLE_DEVICE_ID

//#ifdef PLATFORM_ZYNQMP // not sure if this is required, I am assuming it will remain the same across, kcu105 or kcu116 TODO
//#define GPIO_OFFSET				78
//#else
//#define GPIO_OFFSET				54
//#endif

//#define ADC_DDR_BASEADDR			(XPAR_DDR_MEM_BASEADDR + 0x800000)
//#define DAC_DDR_BASEADDR			(XPAR_DDR_MEM_BASEADDR + 0x900000)
//#endif

//#define RX_CORE_BASEADDR			XPAR_AXI_AD9680_TPL_ADC_TPL_CORE_BASEADDR
//#define TX_CORE_BASEADDR			XPAR_AXI_AD9144_TPL_DAC_TPL_CORE_BASEADDR

//#define RX_DMA_BASEADDR				XPAR_AXI_AD9680_DMA_BASEADDR
//#define TX_DMA_BASEADDR				XPAR_AXI_AD9144_DMA_BASEADDR

//#define RX_JESD_BASEADDR			XPAR_AXI_AD9680_JESD_RX_AXI_BASEADDR
//#define TX_JESD_BASEADDR			XPAR_AXI_AD9144_JESD_TX_AXI_BASEADDR

//#define RX_XCVR_BASEADDR			XPAR_AXI_AD9680_XCVR_BASEADDR
///#define TX_XCVR_BASEADDR			XPAR_AXI_AD9144_XCVR_BASEADDR
//#else
#define SPI_DEVICE_ID				0
//#define GPIO_DEVICE_ID				0

//#define GPIO_OFFSET				0

#define SPI_BASEADDR				SYS_SPI_BASE
//#define GPIO_BASEADDR				SYS_GPIO_OUT_BASE

//#define ADC_DDR_BASEADDR			(SYS_DDR3_CNTRL_ARCH_BASE + 0x800000)
//#define DAC_DDR_BASEADDR			(SYS_DDR3_CNTRL_ARCH_BASE + 0x900000)

//#define RX_CORE_BASEADDR			AXI_AD9680_CORE_BASE
//#define TX_CORE_BASEADDR			AXI_AD9144_CORE_BASE + 0x4000

//#define RX_DMA_BASEADDR				AXI_AD9680_DMA_BASE
//#define TX_DMA_BASEADDR				AXI_AD9144_DMA_BASE

//#define RX_JESD_BASEADDR			AD9680_JESD204_LINK_RECONFIG_BASE
//#define TX_JESD_BASEADDR			AD9144_JESD204_LINK_RECONFIG_BASE

//#define RX_XCVR_BASEADDR			AD9680_JESD204_LINK_MANAGEMENT_BASE
//#define TX_XCVR_BASEADDR			AD9144_JESD204_LINK_MANAGEMENT_BASE

//#define RX_A10_FPLL_BASEADDR			AD9680_JESD204_LINK_PLL_RECONFIG_BASE
//#define TX_A10_FPLL_BASEADDR			AD9144_JESD204_LINK_PLL_RECONFIG_BASE

//#define TX_PLL_BASEADDR				AD9144_JESD204_LANE_PLL_RECONFIG_BASE
//#define RX_PLL_BASEADDR				AD9680_JESD204_LINK_PLL_RECONFIG_BASE

//#define RX_ADXCFG_0_BASEADDR			AVL_ADXCFG_0_RCFG_S1_BASE
//#define RX_ADXCFG_1_BASEADDR			AVL_ADXCFG_1_RCFG_S1_BASE
//#define RX_ADXCFG_2_BASEADDR			AVL_ADXCFG_2_RCFG_S1_BASE
//#define RX_ADXCFG_3_BASEADDR			AVL_ADXCFG_3_RCFG_S1_BASE
//#define TX_ADXCFG_0_BASEADDR			AVL_ADXCFG_0_RCFG_S0_BASE
//#define TX_ADXCFG_1_BASEADDR			AVL_ADXCFG_1_RCFG_S0_BASE
//#define TX_ADXCFG_2_BASEADDR			AVL_ADXCFG_2_RCFG_S0_BASE
//#define TX_ADXCFG_3_BASEADDR			AVL_ADXCFG_3_RCFG_S0_BASE
//#endif
// TO DO fifo buffer config might create issues. 
//#define GPIO_TRIG				(GPIO_OFFSET + 43)
//#define GPIO_ADC_PD				(GPIO_OFFSET + 42)
//#define GPIO_DAC_TXEN				(GPIO_OFFSET + 41)/
//#define GPIO_DAC_RESET				(GPIO_OFFSET + 40)
//#define GPIO_CLKD_SYNC				(GPIO_OFFSET + 38)
//#define GPIO_ADC_FDB				(GPIO_OFFSET + 36)
//#define GPIO_ADC_FDA				(GPIO_OFFSET + 35)
//#define GPIO_SPI_EN                 (GPIO_OFFSET + 35)
///#define GPIO_DAC_IRQ				(GPIO_OFFSET + 34)
//#define GPIO_CLKD_STATUS_1			(GPIO_OFFSET + 33)
//#define GPIO_CLKD_STATUS_0			(GPIO_OFFSET + 32)


#endif /* _PARAMETERS_H_ */
